export default {
    site: {
        // Name of the site this instance is deployed to
        name: 'Melbourne High School',
        // The URL that this instance is deployed at
        hostname: 'bcc.angustrau.me'
    },
    // The URL of the API endpoint
    apiEndpoint: '/api',
    push: {
        // The public key generated by the server for push
        applicationServerKey: "BApjadt4rIrBKKB90OOMNrf0Ns7IEyak0FlKusY0MGCN5fSGkXYLHdUKOv0rX_C582EU5vdfWAbngNjCM_joCp8"
    }
}